version: '3'

services:
  app:
    image: companionapp-1.0.jar
    build: ./
    ports:
      - "8080:7070"
    depends_on:
      - db
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=companion_db